info:
  name: Delete Inventory
  type: http
  seq: 5

http:
  method: DELETE
  url: "{{BaseUrl}}/api/inventories/:id"
  auth: inherit
  params:
    - name: id
      value: "{{inventoryId}}"
      type: path
      enabled: true

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
