info:
  name: Get Inventory by Id
  type: http
  seq: 2

http:
  method: GET
  url: "{{BaseUrl}}/api/inventories/:id"
  auth: inherit
  params:
    - name: id
      value: "{{inventoryId}}"
      type: path
      enabled: true

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
